// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_code_avail from "./routes/api/[code]/avail.ts";
import * as $api_realtime from "./routes/api/realtime.ts";
import * as $index from "./routes/index.tsx";
import * as $CountryIsland from "./islands/CountryIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/[code]/avail.ts": $api_code_avail,
    "./routes/api/realtime.ts": $api_realtime,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CountryIsland.tsx": $CountryIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
